"""general.h generation (CHERI capability layout, perms, otypes, typedefs).

Called from GenCHeri.py:  generate(cfg) -> text of general.h
"""

# Hardware permissions; user-defined perms are appended after these
HW_PERMS = [
    "GLOBAL", "PERMIT_EXECUTE", "PERMIT_LOAD", "PERMIT_STORE", "PERMIT_LOAD_CAP",
    "PERMIT_STORE_CAP", "PERMIT_STORE_LOCAL_CAP", "PERMIT_SEAL", "PERMIT_INVOKE",
    "PERMIT_UNSEAL", "PERMIT_ACC_SYS_REGS", "PERMIT_SET_CID",
]
FIELD_NAMES = {"P": "PERM", "O": "OTYPE", "F": "FLAG", "B": "BOUND"}
# Reserved bits inside the bound region (IE, L7, T, TE, BE ...). Free B bits = bound region - reserved
BOUND_RESERVED = {1: 10, 2: 11}

#Sayak v_1
# def c_type(width):
#     return "uint32_t" if width <= 32 else "uint64_t" if width <= 64 else "unsigned __int128"

#Sayak: v_2 Select the next possible bit width
# def c_type(width):
#     """Smallest unsigned C type that holds `width` bits (8/16/32/64)."""
#     for bits in (8, 16, 32, 64):
#         if width <= bits:
#             return f"uint{bits}_t"
#     return "unsigned __int128"

#Sayak: v_3 Select the next possible bit width
def type_bits(width):
    """Storage size in bits (8/16/32/64) of the smallest unsigned type that holds `width` bits."""
    for bits in (8, 16, 32, 64):
        if width <= bits:
            return bits
    raise ValueError(f"{width} bits does not fit in 64 bits")

def c_type(width):
    """Smallest unsigned C type that holds `width` bits (8/16/32/64)."""
    return f"uint{type_bits(width)}_t"

def spare_span(cfg):
    """Absolute (bot, top) of the spare bits (bound region minus reserved) -> CAP_BOUND_* in general.h."""
    base = cfg["pos"]["B"][0]
    be_w = 2 if cfg["template"] == 1 else 3
    spare = cfg["widths"]["B"] - BOUND_RESERVED[cfg["template"]]
    return base + be_w, base + be_w + spare - 1


#Sayak : Generate the template for generating the General.h
def generate(cfg):
    meta_w, addr_w = cfg["meta_w"], cfg["addr_w"]
    widths, order, pos = cfg["widths"], cfg["order"], cfg["pos"]
    addr_t = "uint32_t" #if addr_w <= 32 else "uint64_t"
    # Sayak: Templates 1/2: BOUND macros cover only the free B bits (bound region minus reserved
    # bits); printed only if at least one B bit is left. Template 3: whole 64-bit bound.
    if cfg["template"] == 3:
        b_bits, b_bot, b_top = widths["B"], pos["B"][0], pos["B"][1]
    else:
        b_bits = widths["B"] - BOUND_RESERVED[cfg["template"]]
        b_bot, b_top = spare_span(cfg)
        
    # bound_defs = (f"#define CAP_BOUND_TOP {b_top}\n#define CAP_BOUND_BOT {b_bot}\n\n"
    #               if b_bits > 0 else "")

    #Sayak: Hard coded Perms << Defined above
    hw_lines = "".join(f"\t{nm},\n" if i else f"\t{nm} = 0,\n" for i, nm in enumerate(HW_PERMS))
    #Sayak: Add user defined Perms after hard coded perms
    hw_lines += "".join(f"\t{nm}, // user-defined\n" for nm in cfg["perm_names"])
    otype_lines = "".join(f"\t{nm} = Unsealed - {i + 3},\n" for i, nm in enumerate(cfg["otype_names"]))

    #if meta_w > 32:  ||<-- previous condition v_1 i removed during testing
    if cfg["template"] == 3 : #Sayak: template 3 always uses struct CHERI; templates 1/2 a plain uint32_t
        cheri_def = ("typedef struct CHERI {\n    PERM perms;\n    OTYPE otype;\n"
                     "    FLAG flags;\n  " + c_type(widths["B"]) + " bounds;\n} CHERI;")
                     #Sayak: " + ("uint64_t" if widths["B"] <= 64 else "unsigned __int128") + " bounds;\n} CHERI;")
    else: #for template 1/2
        cheri_def = "typedef uint32_t CHERI; //sayak_G"

    u128 = ("typedef unsigned __int128 uint128_t;\n\n"
            if any(widths[k] > 64 for k in "POF") else "")
    instr = ("#define MIN_INSTR_BYTES 2\n"
             if cfg["compressed"] else "#define MIN_INSTR_BYTES 4\n")

    return f"""#include <cstdint>

#ifndef _GENERAL
#define _GENERAL

// Auto-generated by gen_cheri_header.py (TEMPLATE {cfg['template']})
// Layout (MSB -> LSB): {' | '.join(FIELD_NAMES[f] for f in order)}
// Widths: perm={widths['P']} otype={widths['O']} flag={widths['F']} bound={widths['B']}

{u128}#define CAP_TOP {meta_w - 1}
#define CAP_BOT 0

#define CAP_FLAG_TOP {pos['F'][1]}
#define CAP_FLAG_BOT {pos['F'][0]}
#define CAP_FLAGS_WIDTH ((CAP_FLAG_TOP - CAP_FLAG_BOT) + 1)

#define CAP_OTYPE_TOP {pos['O'][1]}
#define CAP_OTYPE_BOT {pos['O'][0]}
#define MAX_CAP_OTYPE (0b1 << (CAP_OTYPE_TOP - CAP_OTYPE_BOT + 1)) //Max value of otype is 1 less than this

#define CAP_PERM_TOP {pos['P'][1]}
#define CAP_PERM_BOT {pos['P'][0]}

#define ADDR_BITS 32
#define CAP_LEN {32 + meta_w}
#define BYTES_PER_TAG (CAP_LEN / 8)

{instr}
enum Hardware_perms{{
{hw_lines}}};

// enum Software_perms {{}}

enum Otypes {{
	Unsealed = MAX_CAP_OTYPE - 1,
	Sealed = Unsealed - 1, // Sealed is used as Sentry
	Reserved = Unsealed - 2,
    //User defined Otypes apends below
{otype_lines}}};

enum Flags {{
    CAP_MODE = 0,
}};

typedef {c_type(widths['P'])} PERM; //sayak_G

typedef {c_type(widths['O'])} OTYPE; //sayak_G

typedef {c_type(widths['F'])} FLAG; //Sayak_G

{cheri_def}

struct Capability {{
	{addr_t} addr;
	CHERI caps;
	bool tag;
}};

struct SetBound_Ret {{
	Capability cd;
	bool exact;
	{addr_t} newlen;
	{addr_t} baseMask;
}};

//Set bounds flags
struct SetBound_flag {{
	bool len;
	bool mask;
}};

#endif
"""
